
version: "3"
services:

  proxy-service:
    build: ./proxy
    image : proxy-image
    container_name: proxy-container
    ports:
      - "80:80"
    restart: always
    networks:
      - frontend

  app-service:
    # build: ./hello
    build: .
    image : app-image
    container_name: app-container
    networks:
      - frontend
    restart: always

networks:
  frontend:
